"use client";
import { Switch } from "@/components/ui/form/switch";
import { cn } from "@/lib/utils";
import { Hash } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

type ReferenceInputProps = {
  setValue: (name: any, value: any, options?: any) => void;
  defaultValue?: string | null;
  defaultIsManual?: boolean;
  prefix: string;
  fieldName: string;
  isManualFieldName: string;
  placeholderKey: string;
  autoGeneratedKey: string;
  switchLabelKey: string;
  error?: string;
  isReadOnly?: boolean;
};

export const ReferenceInput = ({
  setValue,
  defaultValue,
  defaultIsManual,
  prefix,
  fieldName,
  isManualFieldName,
  placeholderKey,
  autoGeneratedKey,
  switchLabelKey,
  error,
  isReadOnly,
}: ReferenceInputProps) => {
  const { t } = useTranslation();
  const currentYear = new Date().getFullYear();

  const [isManual, setIsManual] = useState(defaultIsManual);
  const [refNumber, setRefNumber] = useState(() => {
    if (defaultValue) {
      const parts = defaultValue.split("-");
      const suffix = parts.length >= 2 ? parts[1] : "";
      return suffix.slice(0, 4);
    }
    return "";
  });

  const handleToggle = (checked: boolean) => {
    setIsManual(checked);
    setValue(isManualFieldName, checked, { shouldValidate: true });
    if (!checked) {
      setRefNumber("");
      setValue(fieldName, undefined, { shouldValidate: true });
    }
  };

  useEffect(() => {
    if (isManual && refNumber) {
      setValue(fieldName, `${prefix}-${refNumber}-${currentYear}`);
    } else if (!isManual && !isReadOnly) {
      setValue(fieldName, undefined);
    }
  }, [
    isManual,
    refNumber,
    currentYear,
    prefix,
    fieldName,
    setValue,
    isReadOnly,
  ]);

  const handleRefChange = (value: string) => {
    const cleaned = value.replace(/\D/g, "").slice(0, 4);
    setRefNumber(cleaned);
    if (cleaned) {
      setValue(fieldName, `${prefix}-${cleaned}-${currentYear}`);
    } else {
      setValue(fieldName, undefined);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    const isDigit = /^\d$/.test(e.key);
    const isControlKey =
      [
        "Backspace",
        "Delete",
        "ArrowLeft",
        "ArrowRight",
        "Tab",
        "Enter",
        "Escape",
      ].includes(e.key) ||
      e.ctrlKey ||
      e.metaKey;

    if (isDigit && refNumber.length >= 4 && !isControlKey) {
      const { selectionStart, selectionEnd } = e.currentTarget;
      if (selectionStart === selectionEnd) {
        e.preventDefault();
      }
    }
  };

  return (
    <div className="w-full space-y-1.5">
      {/* Reference input container */}
      <div
        className={cn(
          "flex items-center w-full rounded-md border bg-card overflow-hidden transition-all duration-200",
          "focus-within:ring-2 focus-within:ring-primary/20 focus-within:border-primary/50",
          !isManual && "opacity-60 bg-card/30 cursor-not-allowed",
          isReadOnly && "opacity-90 bg-card cursor-default ",
          error
            ? "border-error/50 ring-2 ring-error/10"
            : "border-input/60 hover:border-input",
        )}
      >
        {/* Prefix badge */}
        <div className="flex items-center gap-1.5 px-3 h-9 border-r border-input/50 bg-card shrink-0">
          <Hash className="size-3.5 text-primary/70" />
          <span className="text-sm font-bold text-primary select-none tracking-tight">
            {prefix}
          </span>
        </div>

        {/* Number input wrapper */}
        <div className="flex-1 flex items-center px-1">
          {isReadOnly ? (
            <div className="h-9 w-full flex items-center justify-center">
              <span className="text-sm font-semibold text-card-foreground">
                {refNumber || "—"}
              </span>
            </div>
          ) : isManual ? (
            <input
              type="text"
              inputMode="numeric"
              value={refNumber}
              maxLength={4}
              onKeyDown={handleKeyDown}
              onChange={(e) => handleRefChange(e.target.value)}
              placeholder={t(placeholderKey)}
              className="h-9 w-full bg-card text-sm font-medium text-foreground text-center outline-none placeholder:text-card-foreground/30"
            />
          ) : (
            <div className="h-9 w-full flex items-center justify-center">
              <span className="text-sm text-card-foreground/40 italic">
                {t(autoGeneratedKey)}
              </span>
            </div>
          )}
        </div>

        {/* Year badge */}
        <div className="flex items-center px-3 h-9 border-l border-input/50 bg-card shrink-0">
          <span className="text-sm font-bold text-card-foreground/70 select-none">
            {currentYear}
          </span>
        </div>
      </div>

      {/* Manual toggle - hidden in read-only */}
      {!isReadOnly && (
        <div className="flex items-center justify-between gap-2 px-1">
          {error ? (
            <p className="text-sm font-medium text-error mt-1 px-1">{error}</p>
          ) : (
            <p className="text-sm  text-card-foreground/35 mt-1 px-1"></p>
          )}
          <div className="flex items-center gap-2">
            <label
              htmlFor={`${fieldName}_toggle`}
              className="text-xs font-bold tracking-wider text-card-foreground/60 select-none cursor-pointer hover:text-card-foreground transition-colors"
            >
              {t(switchLabelKey)}
            </label>
            <Switch
              id={`${fieldName}_toggle`}
              checked={isManual}
              onCheckedChange={handleToggle}
            />
          </div>
        </div>
      )}

      {/* Error message */}
    </div>
  );
};
